package com.fast.ekyc.tracking

internal object EventName {
    const val FACE_GUIDE_SHOW = "FACE_GUIDE_SHOW"
    const val FACE_GUIDE_CLICK_START =
        "FACE_GUIDE_CLICK_START"

    const val FACE_CAPTURE_GUIDE_POPUP_SHOW = "FACE_CAPTURE_GUIDE_POPUP_SHOW"
    const val FACE_CAPTURE_GUIDE_POPUP_CLICK_CONFIRM =
        "FACE_CAPTURE_GUIDE_POPUP_CLICK_CONFIRM"

    const val FACE_CAPTURE_SHOW = "FACE_CAPTURE_SHOW"
    const val FACE_CAPTURE_RECORD_RESULT = "FACE_CAPTURE_RECORD_RESULT"

    const val CARD_CAPTURE_GUIDE_HC_POPUP_SHOW = "CARD_CAPTURE_GUIDE_HC_POPUP_SHOW"
    const val CARD_CAPTURE_GUIDE_HC_POPUP_CLICK_UNDERSTAND =
        "CARD_CAPTURE_GUIDE_HC_POPUP_CLICK_UNDERSTAND"

    const val CARD_CAPTURE_SHOW = "CARD_CAPTURE_SHOW"
    const val CARD_CAPTURE_SWITCH_AUTO_CAPTURE =
        "CARD_CAPTURE_SWITCH_AUTO_CAPTURE"

    const val CARD_PREVIEW_SHOW = "CARD_PREVIEW_SHOW"
    const val CARD_PREVIEW_CLICK_BUTTON_CONFIRM =
        "CARD_PREVIEW_CLICK_BUTTON_CONFIRM"
    const val CARD_PREVIEW_CLICK_BUTTON_BACK =
        "CARD_PREVIEW_CLICK_BUTTON_BACK"
    const val CARD_PREVIEW_CLICK_BUTTON_TAKE_AGAIN =
        "CARD_PREVIEW_CLICK_BUTTON_TAKE_AGAIN"

}