object BuildDependenciesVersions {
    const val GRADLE = "7.0.2"
    const val KOTLIN = "1.6.21"
    const val COROUTINES = "1.5.1-native-mt"
    const val CORE_KTX = "1.2.0"
    const val APPCOMPAT = "1.3.1"
    const val FRAGMENT = "1.4.0"
    const val NAVIGATION = "2.3.5"
    const val CONSTRAIN_LAYOUT = "2.1.3"
    const val REYCLERVIEW = "1.1.0"
    const val MATERIAL_COMPONENTS = "1.6.0"
    const val FLEX_BOX = "3.0.0"
    const val SPINNER_DATE_PICKER = "2.0.1"
    const val SHIMMER_FRAME_LAYOUT = "0.5.0"
    const val MULTIDEX = "2.0.1"
    const val LIFECYCLE = "2.4.0"
    const val RETROFIT = "2.6.4"
    const val OKHTTP = "4.7.2"
    const val GSON = "2.8.9"
    const val ROOM = "2.3.0"
    const val TIMBER = "4.7.1"
    const val DAGGER = "2.47"
    const val WORK_MANAGER = "2.7.1"
    const val RECYCLER_VIEW = "1.1.0"

    const val SWIPE_REFRESH = "1.0.0"
    const val PAGING = "2.1.1"
    const val PAGING_3 = "3.0.0"
    const val GLIDE = "4.11.0"
    const val CARDVIEW = "1.0.0"
    const val KODEIN_DI = "7.4.0"
    const val FIREBASE_DATABASE = "19.6.0"
    const val FIREBASE_MESSAGING = "21.0.0"
    const val FIREBASE_AUTH = "20.0.1"
    const val FIREBASE_ANALYTIC = "18.0.0"
    const val FIREBASE_CRASHLYTIC = "17.3.0"
    const val FIREBASE_CRASHLYTIC_GRADLE = "2.4.1"
    const val FIREBASE_REMOTE_CONFIG = "20.0.1"
    const val FIREBASE_FIRESTORE = "22.0.0"
    const val FIREBASE_PERF = "19.0.10"
    const val FIREBASE_PERF_PLUGIN = "1.3.1"
    const val FIREBASE_DYNAMIC_LINK = "19.1.0"
    const val FIREBASE_BOM = "28.4.2"
    const val GOOGLE_PLAY_SERVICES = "17.0.0"
    const val EXOPLAYER = "2.15.1"
    const val FABRIC = "1.31.2"
    const val GRGIT = "4.1.1"
    const val GOOGLE_SERVICES = "4.3.3"
    const val COROUTINE_PLAY_SERVICE = "1.3.6"
    const val CAMERA_VIEW = "2.7.1"
    const val CAMERAX_CAMERA2 = "1.0.1"
    const val CAMERAX_CORE = "1.0.1"
    const val CAMERAX_LIFECYCLE = "1.0.1"
    const val CAMERAX_VIEW = "1.0.0-alpha27"
    const val MLKIT = "24.0.1"
    const val MLKIT_BARCODE_MODEL = "16.0.1"
    const val GOOGLE_BARCODE_SCANNING = "17.0.0"
    const val GOOGLE_BARCODE_MODEL = "16.1.4"
    const val SUNMI_PRINTER = "1.0.13"
    const val MP_CHART = "3.1.0"
    const val MAP_STRUCT = "1.3.1.Final"
    const val MAP_STRUCT_KOTLIN_BUILDER = "1.3.1.2"
    const val PLAY_CORE = "1.8.0"
    const val PLAY_CORE_KTX = "1.8.1"
    const val PROTOBUF = "3.11.1"
    const val DESUGAR_JDK_LIBS = "1.1.5"

    // React Native
    const val JSC_FLAVOR = "+"

    // Debug
    const val LEAK_CANARY = "2.8.1"
    const val DEBUG_DB = "v1.0.6"

    // Tests
    const val JUNIT = "4.12"
    const val JUNIT_EXT = "1.1.0"
    const val MOCKITO = "3.0.0"
    const val EXT = "1.1.0"
    const val ESPRESSO = "3.2.0"
}

